[package]
name = "rust-tele-bot"
version = "0.1.0"
authors = ["Ilya <crusadergo@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.14"
reqwest = "0.9"
